### ISSUE TITLE
Sample list

### ISSUE THREAD

**Issue by f6v** [single-cell-BGI/scCAT#3]
Dear @shiquan @Liang-BGI,

Thank you for sharing the pipeline. I was wondering, can I get the sample list somewhere? I checkout the SRA data out and can't figure out which cells should be assigned to which files. For example, does `SRX5138456`(`scCAT_Blastocyst_RNA_558`) entry contain both reads? And how do I match ATAC and RNA FASTA files to the cells? 

Kind regards

**Comment by Liang-Wu-01** [comment]
@f6v Dear Igor. 
Sorry for the delayed reply and thanks for interesting in our datasets. 
I am not sure about your means about "does entry contain both reads", we uploaded the raw reads of each sample.  Is your faced some problem here?
AND you can match the RNA and ATAC from the same cell according to the library name which you can download from https://www.ncbi.nlm.nih.gov/Traces/study/?query_key=2&WebEnv=MCID_601a04715f1d943488016299&o=acc_s%3Aa. 
e.g., scCAT_Blastocyst_RNA_558 and scCAT_Blastocyst_ATAC_558 are the RNA and ATAC from the cell name as Blastocyst_558.

bests,

Liang

**Comment by f6v** [comment]
Thanks! I was just confused about downloading files from SRA. `fastq-dump` downloads both reads into one file unless I use `--split-files` option. I needed that as your pipeline expects two fasta files per sample.
