### ISSUE TITLE
soap2 index

### ISSUE THREAD

**Issue by f6v** [single-cell-BGI/scCAT#4]
Hi,

I'm trying to run the pipeline to re-align the data to hg38, and to obtain the sam and bed files. 
However, I think soap2 is a thing of the past, as I can't even access the web site. Do you know a way of obtaining that rRNA index? Or maybe you could point me to the alternative? 

Kind regards

**Comment by shiquan** [comment]
For  ATACseq, BWA is suguested. and for RNA, STAR is an option.
